version: '2'
services:
  user-app:
    image: user-app-dock
    build: MovieCruiserAuthenticationService/
    network_mode: host
    restart: always
    depends_on:
      - movie-mysql
    ports:
      - "8088:8088"
    expose:
      - 8088

  movie-app:
    image: movie-app-dock
    build: MovieCruiserAppService/
    network_mode: host
    restart: always
    depends_on:
      - movie-mysql
    ports:
      - "8081:8081"
    expose:
      - 8081

  movie-client-app:
    image: movie-client-app-dock
    build: MovieCruiserAppClient/
    network_mode: host
    restart: always
    ports:
      - "4200:4200"
    expose:
      - 4200

  movie-mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    network_mode: host
    environment:
      MYSQL_DATABASE: moviedb
      MYSQL_USER: app-root
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
